import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";

import MainNavigation from "@/components/Header/MainNavigation";
import QueryClientWrapper from "@/components/Shared/QueryClient/QueryClientProvider";

import { Content, PageContainer } from "../components/Footer/FooterStyles";
import AuthProvider from "../context/auth-context";
import CartContextProvider from "../context/cart/cart-context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SessionProvider>
          <QueryClientWrapper>
            <AuthProvider>
              <CartContextProvider>
                <PageContainer>
                  <MainNavigation />
                  <Content>{children}</Content>
                </PageContainer>
              </CartContextProvider>
            </AuthProvider>
          </QueryClientWrapper>
        </SessionProvider>
      </body>
    </html>
  );
}
